### ISSUE TITLE
PGID and PUID

### ISSUE THREAD

**Issue by amd93** [alfonder/torrentmonitor-dockerized#23]
Hi,

Can you please add PGID and PUID in environment?

Thanks.

**Comment by alfonder** [comment]
Please, explain, where to use those values.

**Comment by amd93** [comment]
Using the PUID and PGID allows containers to map the container's internal user to a user on the host machine. 

For example: https://docs.linuxserver.io/general/understanding-puid-and-pgid

Thanks..

**Comment by amd93** [comment]
Hello, sorry but it's not working for docker compose....

`version: '3'

services:
  torrentmonitor:
    container_name: ${SERVICENAME}
    image: alfonder/torrentmonitor:${TM_TAG}
    restart: unless-stopped
    ports:
      - ${LISTEN_PORT}:80
    volumes:
      - ${DATA_DIR}/torrents:/data/htdocs/torrents
      - ${DATA_DIR}/db:/data/htdocs/db
      - ${DATA_DIR}/logs:/data/htdocs/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - PHP_TIMEZONE=${TIMEZONE}
      - CRON_TIMEOUT=${SCHEDULE}`

`# Specific image tag
TM_TAG=latest

# Container name to use via CLI
SERVICENAME=torrentmonitor

# Port for web-interface
LISTEN_PORT=8081

# Directory for container's persistent data
DATA_DIR=/media/volume1/data/torrentmonitor

# PUID User
PUID=1001

# PGID Group
PGID=100

# Service start schedule in Cron format
SCHEDULE="*/30 8-22 * * *"

# TImezone for web-interface
TIMEZONE="Europe/Moscow"`
